#version: "3"

services:
  server:
    container_name: server
    image: nginx:latest
    volumes:
      - ./docker-data/server/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:5173:5173"
    depends_on:
      - translator
    networks:
        - common
  translator:
    container_name: translator
    build:
      context: .
      dockerfile: ./docker-data/images/translator/Dockerfile
    links:
      - database
    working_dir: '/var/www/html'
    volumes:
      - ./docker-data/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
      - ./docker-data/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
        - common
  database:
    container_name: database-mysql
    image: mysql:8.4.2
    restart: always
    volumes:
      - ./docker-data/database/data:/var/lib/mysql
    environment:
      MYSQL_USER: recipe
      MYSQL_PASSWORD: er54z4q9
      MYSQL_ROOT_PASSWORD: er54z4q9
      MYSQL_DATABASE: recipe
      MYSQL_ROOT_HOST: '%'
    ports:
      - "127.0.0.1:3306:3306"
    networks:
        - common
  mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "127.0.0.1:1025:1025"
        - "127.0.0.1:8025:8025"
      networks:
        - common

networks:
  common:
    driver: bridge
