version: "3"

services:
  server:
    container_name: server
    image: nginx:latest
    volumes:
      - ./docker-data/server/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - '${APP_PORT:-80}:80'
      - '${APP_PORT:-5173}:5173'
    depends_on:
      - translator
    networks:
      - common
  translator:
    container_name: translator
    build:
      context: .
      dockerfile: ./docker-data/images/translator/Dockerfile
    links:
      - database
    working_dir: '/var/www/html'
    volumes:
      - ./docker-data/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
    networks:
      - common
  database:
    container_name: database-mysql-test
    image: mysql:8.4.2
    restart: always
    volumes:
      - ./docker-data/database/data:/var/lib/mysql
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - common
  mailhog:
    container_name: mailhog-test
    image: mailhog/mailhog:latest
    ports:
      - '${MAIL_PORT:-1025}:1025'
      - '8025:8025'
    networks:
      - common

networks:
  common:
    driver: bridge
